spring:
  datasource:
    username: root
    password: a123
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:fun/fengwk/automapper/example/mapper/*.xml